[package]
name = "reef"
description = "An abstraction of an entire CAP-style network"
version = "0.1.0"
authors = ["Jeb Bearer <jeb.bearer@translucence.net"]
edition = "2018"

[dependencies]
arbitrary = { version="1.0", features=["derive"] }
arbitrary-wrappers = { git = "ssh://git@github.com/SpectrumXYZ/arbitrary-wrappers.git" }
ark-serialize = { version = "0.3.0", features = ["derive"] }
commit = { git = "ssh://git@github.com/SpectrumXYZ/commit.git", rev = "f48cd52c59755eade0605111826eef3df6abdcf8" }
funty = "=1.1.0"
itertools = "0.10.1"
jf-cap = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/cap.git", rev = "5d9f71ea796a3107700809bd0cd343ad48bb5166" }
serde = { version = "1.0", features = ["derive"] }
snafu = { version = "0.6.10", features = ["backtraces"] }
strum_macros = "0.20.1"

[dev-dependencies]
lazy_static = "1.4.0"
rand_chacha = { version = "0.3.1", features = ["serde1"] }
