[package]
name = "reef"
description = "An abstraction of an entire AAP-style network"
version = "0.1.0"
authors = ["Jeb Bearer <jeb.bearer@translucence.net"]
edition = "2018"

[dependencies]
ark-serialize = { version = "0.3.0", features = ["derive"] }
itertools = "0.10.1"
jf-aap = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish-apps.git", rev = "1f1f11e7ed8a6e3b012de58e94ca9b905d468d9b"}
serde = { version = "1.0", features = ["derive"] }
snafu = { version = "0.6.10", features = ["backtraces"] }
strum_macros = "0.20.1"
