name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Outdated Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
          default: true
          components: rustfmt, clippy

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v1

      - name: Format Check
        run: cargo fmt -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ github.token }}
          args: --workspace -- -D warnings

      - name: Audit
        run: cargo audit --ignore RUSTSEC-2020-0159 --ignore RUSTSEC-2020-0071

      - name: Test
        run: |
          cargo test --workspace --release --no-run
          cargo test --workspace --release --verbose -- -Zunstable-options --report-time --test-threads 2
        timeout-minutes: 30
